package biblioteca.udb;

public class Devoluciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Devoluciones.class.getName());

    /**
     * Creates new form Devoluciones
     */
    public Devoluciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoEjemplar1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnRealizarDevolucion1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaResultados1 = new javax.swing.JTextArea();
        txtIdUsuario1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setText("Devoluciones");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Codigo ejemplar:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("ID usuario:");

        btnRealizarDevolucion1.setText("Realizar Devolucion");
        btnRealizarDevolucion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarDevolucion1ActionPerformed(evt);
            }
        });

        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        areaResultados1.setColumns(20);
        areaResultados1.setRows(5);
        jScrollPane2.setViewportView(areaResultados1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRealizarDevolucion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar1)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodigoEjemplar1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(txtIdUsuario1))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoEjemplar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRealizarDevolucion1)
                    .addComponent(btnCancelar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarDevolucion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarDevolucion1ActionPerformed
        try {
            // Obtener datos del formulario
            String idUsuarioTexto = txtIdUsuario1.getText();
            String codigoEjemplar = txtCodigoEjemplar1.getText();

            // Validar campos vacíos
            if (idUsuarioTexto.isEmpty() || codigoEjemplar.isEmpty()) {
                areaResultados1.setText("Error: Todos los campos son obligatorios");
                return;
            }

            // Convertir datos
            int idUsuario = Integer.parseInt(idUsuarioTexto);

            // Crear instancia de GestionDevoluciones (debe tener los métodos necesarios)
           GestionDevoluciones gestionDevoluciones = new GestionDevoluciones(); 

            // Verificar que el ejemplar está prestado al usuario
            if (!gestionDevoluciones.ejemplarPrestadoAUsuario(idUsuario, codigoEjemplar)) {
                areaResultados1.setText("Error: No se encontró un préstamo activo de este ejemplar para el usuario.");
                return;
            }

            // Calcular mora y obtener días de mora y multa (método dentro de GestionDevoluciones)
            int diasMora = gestionDevoluciones.calcularDiasMora(idUsuario, codigoEjemplar);
            double multa = 0.0;
            if (diasMora > 0) {
                // tarifaMoraDiaria puede venir de configuraciones o una constante
                double tarifaMoraDiaria = gestionDevoluciones.obtenerTarifaMoraDiaria();
                multa = diasMora * tarifaMoraDiaria;
            }

            // Registrar devolución
            boolean resultado = gestionDevoluciones.realizarDevolucion(idUsuario, codigoEjemplar);

            // Mostrar resultado y detalles
            if (resultado) {
                String mensaje = "Devolución realizada exitosamente.\n";
                if (multa > 0) {
                    mensaje += "Con mora de " + diasMora + " días.\n";
                    mensaje += "Multa a pagar: $" + multa + "\n";
                } else {
                    mensaje += "¡No tiene mora!";
                }
                areaResultados1.setText(mensaje);

                // Limpiar campos
                txtIdUsuario1.setText("");
                txtCodigoEjemplar1.setText("");
            } else {
                areaResultados1.setText("Error: No se pudo registrar la devolución. Verifique los datos.");
            }
        } catch (NumberFormatException ex) {
            areaResultados1.setText("Error: El ID de usuario debe ser un número válido");
        } catch (Exception ex) {
            areaResultados1.setText("Error inesperado: " + ex.getMessage());
            ex.printStackTrace();
        }
        }
        // TODO add your handling code here:
    //GEN-LAST:event_btnRealizarDevolucion1ActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed

        // Limpiar campos de texto
        txtIdUsuario1.setText("");
        txtCodigoEjemplar1.setText("");

        // Limpiar la zona de resultados
        areaResultados1.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Devoluciones().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultados1;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnRealizarDevolucion1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCodigoEjemplar1;
    private javax.swing.JTextField txtIdUsuario1;
    // End of variables declaration//GEN-END:variables

}