/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.udb;
import biblioteca.udb.menu.menuVista;
import javax.swing.JFrame;

/**
 *
 * @author noche
 */
public class FormularioPrestamos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioPrestamos.class.getName());
    private JFrame menuPrincipal;
    /**
     * Creates new form FormularioPrestamos
     */
    public FormularioPrestamos() {
        initComponents();
    }
    
        public FormularioPrestamos(JFrame menu) {
        this.menuPrincipal = menu;  // Guardar referencia
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoEjemplar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboDiasPrestamo = new javax.swing.JComboBox<>();
        btnRealizarPrestamo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Realizar Prestamos");
        setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel1.setText("ID Usuario:");

        jLabel2.setText("Codigo Ejemplar:");

        jLabel3.setText("Dias de Prestamos:");

        comboDiasPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "7", "14", "21", "30" }));

        btnRealizarPrestamo.setText("Realizar Prestamo");
        btnRealizarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPrestamoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Volver al menu");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        areaResultados.setEditable(false);
        areaResultados.setColumns(20);
        areaResultados.setLineWrap(true);
        areaResultados.setRows(5);
        areaResultados.setWrapStyleWord(true);
        jScrollPane1.setViewportView(areaResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRealizarPrestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(121, 121, 121)
                        .addComponent(comboDiasPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41)
                        .addComponent(txtCodigoEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboDiasPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnRealizarPrestamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        txtIdUsuario.getAccessibleContext().setAccessibleName("txtxtidUsuario");
        jLabel2.getAccessibleContext().setAccessibleName("jLabel2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPrestamoActionPerformed
    try {
        // Obtener datos del formulario
        String idUsuarioTexto = txtIdUsuario.getText();
        String codigoEjemplar = txtCodigoEjemplar.getText();
        String diasTexto = (String) comboDiasPrestamo.getSelectedItem();
        
        // Validar campos vacíos
        if (idUsuarioTexto.isEmpty() || codigoEjemplar.isEmpty()) {
            areaResultados.setText("Error: Todos los campos son obligatorios");
            return;
        }
        
        // Convertir datos
        int idUsuario = Integer.parseInt(idUsuarioTexto);
        int diasPrestamo = Integer.parseInt(diasTexto);
        
        // Crear instancia de GestionPrestamos
        GestionPrestamos gestionPrestamos = new GestionPrestamos();
        
        // Validar que el usuario no tenga mora
        if (gestionPrestamos.usuarioTieneMora(idUsuario)) {
            areaResultados.setText("Error: El usuario tiene mora pendiente.\n" +
                                  "No se puede realizar el préstamo.\n" +
                                  "Por favor, pagar la mora antes de solicitar nuevos préstamos.");
            return;
        }
        
        // Validar que el ejemplar esté disponible
        if (!gestionPrestamos.ejemplarDisponible(codigoEjemplar)) {
            areaResultados.setText("Error: El ejemplar no está disponible.\n" +
                                  "Puede estar prestado o no existe en el sistema.");
            return;
        }
        
        // Realizar el préstamo
        boolean resultado = gestionPrestamos.realizarPrestamo(idUsuario, codigoEjemplar, diasPrestamo);
        
        if (resultado) {
            areaResultados.setText("¡Préstamo realizado exitosamente!\n\n" +
                                  "Usuario ID: " + idUsuario + "\n" +
                                  "Ejemplar: " + codigoEjemplar + "\n" +
                                  "Días de préstamo: " + diasPrestamo + "\n\n" +
                                  "Por favor, devolver el ejemplar antes de la fecha límite.");
            
            // Limpiar campos
            txtIdUsuario.setText("");
            txtCodigoEjemplar.setText("");
            comboDiasPrestamo.setSelectedItem("7");
        } else {
            areaResultados.setText("Error: No se pudo realizar el préstamo.\n" +
                                  "Verifique los datos e intente nuevamente.");
        }
        
    } catch (NumberFormatException ex) {
        areaResultados.setText("Error: El ID de usuario debe ser un número válido");
    } catch (Exception ex) {
        areaResultados.setText("Error inesperado: " + ex.getMessage());
        ex.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarPrestamoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();  
        
         if (menuPrincipal != null) {
            menuPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioPrestamos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultados;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRealizarPrestamo;
    private javax.swing.JComboBox<String> comboDiasPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigoEjemplar;
    private javax.swing.JTextField txtIdUsuario;
    // End of variables declaration//GEN-END:variables
}
